server:
  port: 7010
spring:
  application:
    name: 'spring-gateway-example'
  profiles:
    active: '@profiles.active@'

  cloud:
    gateway:
      routes:
        - id: demo1  # 路由的标识，要求唯一，默认UUID，
          uri: https://github.com # 目标地址
          predicates:   #断言
            - Path=/lovemooner/** # 请求路径满足Path指定的规则时，才转发
          filters:
            # 值为true则开启认证，false则不开启
            - MyLog=true

        - id: testGatewayFilter1
          uri: http://localhost:8080
          predicates:
            - Path=/hello-demo/gw/filter1
          filters:
            - MyLog=true   # 自定义。值为true则开启认证，false则不开启
            - AddRequestHeader=param1,p1 #添加 header
            - AddRequestParameter=username,zhangsan #添加一个请求参数
            - AddResponseHeader=encryption,false #响应中增加一个 响应头。
            - RemoveRequestHeader=x-token #需要移除的请求头
            - RemoveResponseHeader=x-token #移除响应头
            - RemoveRequestParameter=password #移除请求参数

        - id: AddRequestHeader2
          uri: http://localhost:8080
          predicates:
            - Path=/hello-demo/gw/addRequestHeader2/{userId}
          filters:
            - AddRequestHeader=param2,p2-{userId}

        - id: PrefixPath1
          uri: http://localhost:8080
          predicates:
            - Path=/gw/prefix-path
          filters:
            - PrefixPath=/hello-demo

        # 移除路径前缀
        - id: StripPrefix1
          uri: http://localhost:8080
          predicates:
            - Path=/proxy/hello-demo/**
          filters:
            - StripPrefix=1


#        - uri: https://www.csdn.net
#          predicates:
#              - MyPredicateFactory=/csdn






